<a href="https://colab.research.google.com/github/Salimbhamida/IRM-IA/blob/main/Clustering_lab3_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Post-processing of numerical datset**

<u>To do :</u>

The processed dataset is in a numerical format.

However, it still requires post-processing to ensure good machine learning performance.

The post-processing is a 2-steps process :
- Normalization
- Dimension Reduction

<u>Note :</u> Replace whenever you find #? by a required python code

**1. Load the processed numerical dataset**

In [1]:
# Import pandas
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [50]:
# Load processed numerical employees as a dataframe
df_employees = pd.read_csv("/content/drive/MyDrive/employes_num.csv", header=0, index_col=0)
df_employees.head(3)

salaire    prime  anciennete  etat_civil_celibataire  \
Ali    1200.675000  100.560           5                     1.0   
Sonia  2800.786000  400.876          18                     0.0   
Rahma  2192.082091  130.987           6                     1.0   

       etat_civil_marie  
Ali                 0.0  
Sonia               1.0  
Rahma               0.0

In [10]:
# Since the dataset becomes a numerical matrix, we have to import numpy module
# The subsequent processing will be performed on a matrix
import numpy as np

# To limit the precision of float numbers to 2 when displaying numpy arrays
# Use this trick :
np.set_printoptions(precision=2)

**2. Normalization of the columns**

Column scales are not balanced

They require a normalization processing

We can check this scale unbalancing in variances of variables 'salaire' , 'prime' , 'anciennete' , ... or by the covariance matrix of dataset

In [11]:
# Get the numerical values of the dataset df_ as a numpy matrix X
X=df_employees.values
X

array([[1.20e+03, 1.01e+02, 5.00e+00, 1.00e+00, 0.00e+00],
       [2.80e+03, 4.01e+02, 1.80e+01, 0.00e+00, 1.00e+00],
       [2.19e+03, 1.31e+02, 6.00e+00, 1.00e+00, 0.00e+00],
       [2.50e+03, 3.41e+02, 1.30e+01, 0.00e+00, 1.00e+00],
       [3.10e+03, 2.57e+02, 1.90e+01, 0.00e+00, 1.00e+00],
       [1.30e+03, 1.51e+02, 6.00e+00, 1.00e+00, 0.00e+00],
       [1.10e+03, 1.31e+02, 4.00e+00, 1.00e+00, 0.00e+00],
       [3.00e+03, 2.57e+02, 2.30e+01, 0.00e+00, 1.00e+00],
       [1.51e+03, 1.60e+02, 6.00e+00, 1.00e+00, 0.00e+00],
       [2.70e+03, 4.00e+02, 2.40e+01, 0.00e+00, 1.00e+00],
       [1.20e+03, 2.57e+02, 8.00e+00, 1.00e+00, 0.00e+00],
       [3.70e+03, 5.00e+02, 3.20e+01, 0.00e+00, 1.00e+00]])

**Check data statistics**

To justify the normalization, we should be sure that the data statistics are unbalanced mainly means and variances

In [12]:
# Check the means of the dataset X
# To compute the mean per column of a matrix
# Call np.mean() and pass as arguments :
# - the matrix
# - axis=0
np.mean(X , axis=0)

array([2.19e+03, 2.57e+02, 1.37e+01, 5.00e-01, 5.00e-01])

In [13]:
# Check the variances of the dataset X
# To compute the mean per column of a matrix
# Call np.var() and pass as arguments :
# - the matrix
# - axis=0
np.var(X , axis=0)

array([7.42e+05, 1.53e+04, 7.96e+01, 2.50e-01, 2.50e-01])

**Apply Standard Scaling process**

Standard Scaling is implemented using `sklearn.preprocessing.StandardScaler`

It is a way to normalize the data so that it has :
- a mean (average) of 0
- a standard deviation (variance square) of 1.

Process description :

1. Calculate Mean and Standard Deviation per columns

2. Subtract Mean: It then subtracts the mean from each data point.
   
   -> This operation centers the data around 0, so the new mean is 0.

3. Divide by Standard Deviation: After centering, each data point is divided by the standard deviation.

   -> This step scales the data, making the standard deviation equal to 1.

   Once the normalization is applied, all the data variables (dataset columns) have 0 (means) and 1 (variance)

In [15]:
# Import StandardScaler class from sklearn.preprocessing module
from sklearn.preprocessing import StandardScaler

In [16]:
# Create an instance of StandardScaler class
ss=StandardScaler()

In [17]:
# Call fit() function of ss and pass X as argument
ss.fit(X)

StandardScaler()

In [18]:
# Call transform() of ss and pass X as argument
# It returns the normalized dataset, denoted X_ss
X_ss = ss.transform(X)
X_ss

array([[-1.15, -1.26, -0.97,  1.  , -1.  ],
       [ 0.71,  1.16,  0.49, -1.  ,  1.  ],
       [ 0.  , -1.02, -0.86,  1.  , -1.  ],
       [ 0.36,  0.67, -0.07, -1.  ,  1.  ],
       [ 1.06,  0.  ,  0.6 , -1.  ,  1.  ],
       [-1.03, -0.86, -0.86,  1.  , -1.  ],
       [-1.27, -1.02, -1.08,  1.  , -1.  ],
       [ 0.94,  0.  ,  1.05, -1.  ,  1.  ],
       [-0.8 , -0.79, -0.86,  1.  , -1.  ],
       [ 0.59,  1.15,  1.16, -1.  ,  1.  ],
       [-1.15,  0.  , -0.64,  1.  , -1.  ],
       [ 1.75,  1.96,  2.06, -1.  ,  1.  ]])

**Check statistics of normalized dataset**

After the normalization, we can check the data statistics are now balanced mainly means and variances

In [26]:
# After noramlization, check the means of the columns of dataset X
# They should be almost 0
np.mean(X_ss , axis=0)

array([ 1.67e-16, -7.40e-17,  7.40e-17,  0.00e+00,  0.00e+00])

In [25]:
# After normalization, check the variances or covariance matrix of dataset
# The variance values should be 1
np.var(X_ss, axis=0)

array([1., 1., 1., 1., 1.])

**3. Reduction of the dimension**

The numerical data matrix serves as a representation of population data.

The rows within this matrix represent individuals within the population.

The columns of this matrix correspond to characteristics that describe the population.

Because the data matrix is normalized, it becomes possible to compare these characteristics, revealing potential redundancies.

In such cases, reducing the number of dimensions helps to eliminate redundant information.

We can assess the <font color='red'>correlation</font> between these dimensions by examining the covariance matrix of the normalized data matrix.

**Check dataset statistics**

To justify the dimension reduction, we should be sure that there are <font color='red'>high correlations</font> between dimensions

In [27]:
# Check the covarinace matrix of normalized dataset
# Mainly the non-diagonal values that correpond to correlations between the variables (salaire, prime, ...)
# They are values between [-1, 1]
# If they are close to 0 , it means that there is no correlation
# If they are close to 1 , it means that there is a high correlation
# In this case, it is worth to reduce the dimension (number of variables)
np.cov(X_ss.T , ddof=0)

array([[ 1.  ,  0.79,  0.92, -0.9 ,  0.9 ],
       [ 0.79,  1.  ,  0.88, -0.82,  0.82],
       [ 0.92,  0.88,  1.  , -0.88,  0.88],
       [-0.9 , -0.82, -0.88,  1.  , -1.  ],
       [ 0.9 ,  0.82,  0.88, -1.  ,  1.  ]])

**Principal Component Analysis (PCA)**

In [28]:
# Import PCA class from sklearn.decomposition module
from sklearn.decomposition import PCA

In [29]:
# Create an instance of PCA class
pca=PCA()

In [30]:
# Call the function fit() and pass X_ss as an argument
pca.fit(X_ss)

PCA()

In [31]:
# Check the weight of each variable in
pca.explained_variance_ratio_

array([9.03e-01, 5.11e-02, 3.41e-02, 1.15e-02, 5.86e-34])

**Dimension reduction using PCA**

In [34]:
from sklearn.decomposition import PCA
# Apply PCA with reduced dimension=2
pca=PCA(n_components=2)
pca.fit(X_ss)
X_pca=pca.transform(X_ss)
X_pca

array([[-2.4 , -0.21],
       [ 1.94,  0.13],
       [-1.73, -0.29],
       [ 1.33, -0.29],
       [ 1.65, -0.85],
       [-2.13,  0.1 ],
       [-2.4 , -0.02],
       [ 1.8 , -0.71],
       [-1.99,  0.1 ],
       [ 2.19,  0.32],
       [-1.71,  0.86],
       [ 3.46,  0.86]])

**Check statistics of reduced dataset**

Following dimension reduction, we examine the covariance matrix of the reduced data matrix to confirm that there no longer correlations.

In [35]:
# Check the covarinace matrix of reduced dataset
# Check that the non-diagonal values are reduced to 0.
np.cov(X_pca.T , ddof=0)

array([[4.52e+00, 2.41e-16],
       [2.41e-16, 2.55e-01]])

**Save the transformed dataset**

In [52]:
# To save the reduced normalized dataset, call to_csv() function and pass as arguments :
# - file name 'employes_num_2.csv'
# - header : None because the columns have no labels
# - index : True in order to put employees names as index
df_employes_proc=pd.DataFrame(X_pca, index=df_employees.index)
df_employes_proc

0         1
Ali     -2.402546 -0.212608
Sonia    1.941043  0.133368
Rahma   -1.733598 -0.293676
Salma    1.325917 -0.290596
Ahmed    1.653006 -0.848056
Saleh   -2.127068  0.104101
Ameni   -2.400687 -0.015080
Mehdi    1.803156 -0.713094
Salem   -1.990624  0.097963
Sameh    2.188936  0.315169
Wajdi   -1.712559  0.864386
Moufida  3.455024  0.858123